# Generated by Django 4.0.5 on 2022-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolHash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_raw', models.BinaryField(unique=True)),
                ('view', models.CharField(max_length=10485760)),
            ],
            options={
                'db_table': 'pool_hash',
                'managed': False,
            },
        ),
    ]
