# Generated by Django 4.0.5 on 2022-07-18 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_link', models.CharField(max_length=100)),
                ('version', models.FloatField()),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=100)),
                ('token_num', models.IntegerField()),
                ('start_time', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.DateField(default=django.utils.timezone.now)),
                ('prefer_pool_num', models.IntegerField()),
                ('prefer_wallet_num', models.IntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('registering', 'registering'), ('registered', 'registered'), ('finalized', 'finalized'), ('done', 'done')], default='registering', max_length=15)),
                ('note', models.CharField(max_length=200)),
                ('disclaimer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.disclaimer')),
            ],
        ),
        migrations.CreateModel(
            name='PoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=100)),
                ('pool_id', models.IntegerField()),
                ('prefer_token', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('status', models.CharField(choices=[('registered', 'registered'), ('finalized', 'finalized'), ('done', 'done')], default='registered', max_length=15)),
                ('note', models.CharField(max_length=200)),
                ('disclaimer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.disclaimer')),
            ],
        ),
    ]
