# Generated by Django 4.0.5 on 2022-06-28 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 19, 57, 50, 477098)),
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 19, 57, 50, 477098)),
        ),
    ]
