# Generated by Django 4.0.5 on 2022-07-20 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolregistration',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poolregistration',
            name='email',
            field=models.EmailField(default='01/01/2022', max_length=255, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolregistration',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poolregistration',
            name='pool_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poolregistration',
            name='status',
            field=models.CharField(choices=[('registering', 'registering'), ('registered', 'registered'), ('finalized', 'finalized'), ('done', 'done')], default='registering', max_length=15),
        ),
    ]
