# Generated by Django 3.2.6 on 2022-06-29 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_projectregistration_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 46, 42, 137634)),
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 46, 42, 137634)),
        ),
    ]
