# Generated by Django 3.2.6 on 2022-06-29 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20220629_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 12, 58, 56, 250690)),
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 12, 58, 56, 250690)),
        ),
    ]
