# Generated by Django 3.2.6 on 2022-06-29 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20220629_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='poolregistration',
            name='phone',
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 14, 47, 13, 598346)),
        ),
        migrations.AlterField(
            model_name='projectregistration',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 14, 47, 13, 597348)),
        ),
    ]
