# Generated by Django 3.2.6 on 2022-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
