# Generated by Django 4.0.5 on 2022-06-25 02:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_projectuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_link', models.CharField(max_length=100)),
                ('version', models.FloatField()),
                ('note', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingProjectPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 9, 19, 29, 860453))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 9, 19, 29, 860453))),
            ],
        ),
        migrations.CreateModel(
            name='PoolRegis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pool_addr', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('registered', 'registered'), ('finalized', 'finalized'), ('done', 'done')], default='registered', max_length=15)),
                ('note', models.CharField(max_length=200)),
                ('disclaimer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.disclaimer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token_id', models.CharField(max_length=100)),
                ('token_num', models.IntegerField()),
                ('pool_num', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 9, 19, 29, 859453))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 9, 19, 29, 859453))),
                ('status', models.CharField(choices=[('registered', 'registered'), ('finalized', 'finalized'), ('done', 'done')], default='registered', max_length=15)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='status',
            field=models.CharField(choices=[('creeated', 'creeated'), ('registered', 'registered'), ('activate', 'activate'), ('lock', 'lock')], default='creeated', max_length=15),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user_type',
            field=models.CharField(choices=[('token_distributor', 'token_distributor'), ('pools_owner', 'pools_owner'), ('deligated_users', 'deligated_users')], default='deligated_users', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectRole',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='projectregis',
            name='deligated_users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectregis',
            name='disclaimer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.disclaimer'),
        ),
        migrations.AddField(
            model_name='poolregis',
            name='user_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchingprojectpool',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.poolregis'),
        ),
        migrations.AddField(
            model_name='matchingprojectpool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.projectregis'),
        ),
    ]
