# Generated by Django 4.0.5 on 2022-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_disclaimer_matchingprojectpool_poolregis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingprojectpool',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='matchingprojectpool',
            name='project',
        ),
        migrations.RemoveField(
            model_name='poolregis',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='poolregis',
            name='user_owner',
        ),
        migrations.RemoveField(
            model_name='projectregis',
            name='deligated_users',
        ),
        migrations.RemoveField(
            model_name='projectregis',
            name='disclaimer',
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('activate', 'activate'), ('lock', 'lock')], default='registered', max_length=15),
        ),
        migrations.DeleteModel(
            name='Disclaimer',
        ),
        migrations.DeleteModel(
            name='MatchingProjectPool',
        ),
        migrations.DeleteModel(
            name='PoolRegis',
        ),
        migrations.DeleteModel(
            name='ProjectRegis',
        ),
    ]
