# Generated by Django 3.2.6 on 2022-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_matchingprojectpool_pool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='user_type',
            field=models.CharField(choices=[('token_distributor', 'token_distributor'), ('pools_owner', 'pools_owner'), ('deligated_users', 'deligated_users'), ('admin', 'admin')], default='deligated_users', max_length=20),
        ),
    ]
