# Generated by Django 3.2.6 on 2022-06-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220629_1447'),
        ('accounts', '0009_projectuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.projectregistration'),
        ),
    ]
